dynamic & static libs in iOS
icerockdev/kmm-docs pull request #106
Opened 2022-05-17 10:15 UTC by kramlex

2022-05-17 15:31 UTC, Alex009 requested changes

2022-05-17 15:31 UTC, Alex009 commented on learning/ios/static-dynamic-libs.md
> +При попытке отправить ресурсы (такие как строковые файлы, изображения и т. д.) библиотеки iOS/macOS доставляются вместе с пакетами (Bundle's), содержащими эти ресурсы, об этом можете почитать ниже в
есть различие в работе с ресурсами.
если фреймворк динамический - то его бандл легко получить - Bundle(forClass: <тут класс от фреймворка>)
если статический - то хоть бандл физически и есть в фреймворке, но найти его по классу не удастся. и вообще xcode ресурсы не будет копировать, если дефолтная логика будет (not embeded фреймворк).

2022-05-17 15:31 UTC, Alex009 commented on learning/ios/static-dynamic-libs.md
> +При попытке отправить ресурсы (такие как строковые файлы, изображения и т. д.) библиотеки iOS/macOS доставляются вместе с пакетами (Bundle's), содержащими эти ресурсы, об этом можете почитать ниже в
про это различие надо показать наглядно и пояснить

2022-05-17 15:31 UTC, Alex009 commented on learning/ios/static-dynamic-libs.md
> +Другими словами основное отличие iOS от остальных платформ, так это то, что разработчик не может установить свои динамические модули в общем месте и использовать их из разных приложений. Это связано
точно подписанных по разному, а не возможно)

2022-05-17 15:31 UTC, Alex009 commented on learning/ios/static-dynamic-libs.md
> +- Apple рекомендовала на WWDC использовать не более 6 динамических фреймворков
ссылку бы на пруф)

2022-05-17 15:31 UTC, Alex009 commented on learning/ios/static-dynamic-libs.md
> +- Если несколько модулей используют одну и ту же статическую библиотеку, то это может вызвать проблемы ***duplicate symbols*** из-за дублирования символов в модуле
эта проблема должна быть подробнее разобрана и показана на примере. пример надо отдельным репом на гитхаб залить чтоб можно было скачать потыкать

2022-05-17 15:31 UTC, Alex009 commented on learning/ios/static-dynamic-libs.md
> +После ознакомления со статьей вы наверное уже догадались, что единствено правильного способа устраивать зависимости в iOS проекте нет, и вам нужно выбирать то, что лучше поможет вам решить поставленн
мало) надо обозначить принцип выбора.
важно время запуска - статические либы ускорят.
важен размер приложения - при правильном использовании статические либы дадут лучший результат
есть общий между виджетом и приложением код - делай динамик фреймворк чтоб грузилось один раз
и тд

2022-05-18 03:09 UTC, kramlex commented on learning/ios/static-dynamic-libs.md
> +Другими словами основное отличие iOS от остальных платформ, так это то, что разработчик не может установить свои динамические модули в общем месте и использовать их из разных приложений. Это связано
Но можно же встраивать фреймворк без подписи

2022-05-18 03:13 UTC, Alex009 commented on learning/ios/static-dynamic-libs.md
> +Другими словами основное отличие iOS от остальных платформ, так это то, что разработчик не может установить свои динамические модули в общем месте и использовать их из разных приложений. Это связано
тогда аппстор тебя не пустит - все бинари подписанные должны быть

2022-05-18 03:25 UTC, kramlex commented on learning/ios/static-dynamic-libs.md
> +- Apple рекомендовала на WWDC использовать не более 6 динамических фреймворков
https://www.youtube.com/watch?v=PxV34oZxGLM 29:54 - 30:20 оптимальное значение полдюжины (half a dozen)

2022-05-18 03:26 UTC, kramlex commented on learning/ios/static-dynamic-libs.md
> +- Apple рекомендовала на WWDC использовать не более 6 динамических фреймворков
Но эир было в 2016 году,мб и в вправду стоит убрать упоминание об этом, устройства с того времени стали гораздо быстрее

2022-05-18 05:42 UTC, kramlex commented on learning/ios/static-dynamic-libs.md
> +При попытке отправить ресурсы (такие как строковые файлы, изображения и т. д.) библиотеки iOS/macOS доставляются вместе с пакетами (Bundle's), содержащими эти ресурсы, об этом можете почитать ниже в
👍

2022-05-18 05:42 UTC, kramlex commented on learning/ios/static-dynamic-libs.md
> +Другими словами основное отличие iOS от остальных платформ, так это то, что разработчик не может установить свои динамические модули в общем месте и использовать их из разных приложений. Это связано
поправил 👍

2022-05-18 05:42 UTC, kramlex commented on learning/ios/static-dynamic-libs.md
> +- Apple рекомендовала на WWDC использовать не более 6 динамических фреймворков
отписал что были такие рекомендации, но они, возможно, устарели

2022-05-18 05:42 UTC, kramlex commented on learning/ios/static-dynamic-libs.md
> +- Если несколько модулей используют одну и ту же статическую библиотеку, то это может вызвать проблемы ***duplicate symbols*** из-за дублирования символов в модуле
👍  добавлен пример

2022-05-18 05:43 UTC, kramlex commented on learning/ios/static-dynamic-libs.md
> +После ознакомления со статьей вы наверное уже догадались, что единствено правильного способа устраивать зависимости в iOS проекте нет, и вам нужно выбирать то, что лучше поможет вам решить поставленн
Выводы расширил рекомендациями для каждой цели

2022-05-20 12:43 UTC, Alex009 approved these changes

2022-05-20 12:43 UTC, merged