use domain entities
icerockdev/kmm-docs pull request #135
Opened 2022-07-01 08:39 UTC by anton6tak

2022-07-05 08:01 UTC, Alex009 requested changes

2022-07-05 08:01 UTC, Alex009 commented on university/4-icerock-basics/mock-engine.md
> +Почти любое мобильное приложение оперирует данными из сетевых объектов - посылает запрос, получает ответ, и что-то делает с полученными данными. Объекты, которые отправляет сервер называются сетевыми
также сетевыми будут и те которые мы отправляем на сервер. то есть все классы которые для отправки/приемки по сети используются, непосредственно для сериализации, они сетевые

2022-07-05 08:01 UTC, Alex009 commented on university/4-icerock-basics/mock-engine.md
> +Тогда, если какая-то сетевая сущность изменится, вам всего лишь нужно будет переделать ее маппер в доменную.
надо пример дописать - типа вот сетевая сущность, а вот доменная. и вот как мапятся они.

и + может более полную красивую подробную статью или видео найдешь по теме, вдруг есть?

2022-07-06 07:11 UTC, anton6tak commented on university/4-icerock-basics/mock-engine.md
> +Почти любое мобильное приложение оперирует данными из сетевых объектов - посылает запрос, получает ответ, и что-то делает с полученными данными. Объекты, которые отправляет сервер называются сетевыми
дописал

2022-07-06 07:14 UTC, anton6tak commented on university/4-icerock-basics/mock-engine.md
> +Тогда, если какая-то сетевая сущность изменится, вам всего лишь нужно будет переделать ее маппер в доменную.
добавил пример, нашел только вот такой видосик https://www.youtube.com/watch?v=yUk4NzkdmG8, но он на англ, ну и он не выглядит полезней того, что у нас написано

2022-07-07 09:04 UTC, Alex009 approved these changes

2022-07-07 09:10 UTC, merged