about custom view
icerockdev/kmm-docs pull request #139
Opened 2022-07-05 03:57 UTC by anton6tak

2022-07-05 07:57 UTC, Alex009 requested changes

2022-07-05 07:57 UTC, Alex009 commented on university/2-ios-basics/ui-navigation.md
> +![img.png](media/create-view.png)
вместо img.png стоит указывать имя медиа файла, чтоб было понятнее когда наводишь на картинку незагруженную что там такое

2022-07-05 07:57 UTC, Alex009 commented on university/2-ios-basics/ui-navigation.md
> +![img.png](media/set-filesowner-class.png)
вместо img.png стоит указывать имя медиа файла, чтоб было понятнее когда наводишь на картинку незагруженную что там такое

2022-07-05 07:57 UTC, Alex009 commented on university/2-ios-basics/ui-navigation.md
> +![img.png](media/add-view-to-controller.png)
вместо img.png стоит указывать имя медиа файла, чтоб было понятнее когда наводишь на картинку незагруженную что там такое

2022-07-05 07:57 UTC, Alex009 commented on university/2-ios-basics/ui-navigation.md
> +![img.png](media/use-custom-view.png)
вместо img.png стоит указывать имя медиа файла, чтоб было понятнее когда наводишь на картинку незагруженную что там такое

2022-07-05 07:57 UTC, Alex009 commented on university/2-ios-basics/ui-navigation.md
> +## CustomView
вижу что описано как свою кастом вью сделать и заинтегрировать. но надо еще и кейс сторонней кастом вьюхи описать - он у нас чаще встречается. Когда мы хотим прогрессбар материаловский например подключить в xib напрямую, а не кодом добавлять в верстку.

2022-07-06 03:34 UTC, anton6tak commented on university/2-ios-basics/ui-navigation.md
> +![img.png](media/create-view.png)
поправил

2022-07-06 03:34 UTC, anton6tak commented on university/2-ios-basics/ui-navigation.md
> +![img.png](media/set-filesowner-class.png)
поправил

2022-07-06 03:34 UTC, anton6tak commented on university/2-ios-basics/ui-navigation.md
> +![img.png](media/add-view-to-controller.png)
поправил

2022-07-06 03:34 UTC, anton6tak commented on university/2-ios-basics/ui-navigation.md
> +![img.png](media/use-custom-view.png)
поправил

2022-07-06 03:34 UTC, anton6tak commented on university/2-ios-basics/ui-navigation.md
> +## CustomView
Дописал

2022-07-06 08:42 UTC, merged