draft practice changes
icerockdev/kmm-docs pull request #140
Opened 2022-07-07 11:19 UTC by anton6tak

2022-07-12 03:56 UTC, Alex009 requested changes
@anton6tak сделать страницу "разделение сущностей" с текстом из последнего раздела в "мокирование данных" и с практикой по проверке использования этого подхода

2022-07-12 03:56 UTC, Alex009 commented on university/4-icerock-basics/mvvm.md
> +- Используйте проект, готовый после раздела [Многомодульность](./multimodularity#практическое-задание)
после раздела DI

2022-07-12 03:56 UTC, Alex009 commented on university/4-icerock-basics/navigation.md
> +- Перенесите классы из iOS приложения третьего блока в новое приложение
это уже сделано. тут пункт скорей "берем проект с состояния "ресурсы в общем коде"

2022-07-12 03:56 UTC, Alex009 commented on university/4-icerock-basics/ui-units.md
> +- Реализуйте логику построения списков в общем коде (список репозиториев)
только для списка репозиториев

2022-07-12 05:35 UTC, anton6tak commented on university/4-icerock-basics/mvvm.md
> +- Используйте проект, готовый после раздела [Многомодульность](./multimodularity#практическое-задание)
исправил, добавл страницу entities про сущности

2022-07-12 05:35 UTC, anton6tak commented on university/4-icerock-basics/navigation.md
> +- Перенесите классы из iOS приложения третьего блока в новое приложение
исправил

2022-07-12 05:36 UTC, anton6tak commented on university/4-icerock-basics/ui-units.md
> +- Реализуйте логику построения списков в общем коде (список репозиториев)
дописал

2022-07-13 04:23 UTC, Alex009 approved these changes

2022-07-13 04:23 UTC, merged