instruction for movement workspace dir to other disk - complete
icerockdev/kmm-docs pull request #144
Opened 2022-08-01 17:11 UTC by ExNDY

2022-08-03 09:32 UTC, Alex009 requested changes

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +`export KONAN_DEV_DIR=/Volumes/ExternalDrive/KONAN/.konan`
KONAN_DATA же?

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +  `/%USERNAME%/.gradle`
~/.gradle

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +  `/%USERNAME%/.konan`
~/.konan

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +  `/%USERNAME%/Documents/xCode`
~/Documents/Xcode

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +  `/%USERNAME%/AndroidStudioProjects`
~/AndroidStudioProjects

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +Для экономии времени можем перенести папку .konan из директории `/%USERNAME%/.konan` в заранее созданную нами папку.
~/.konan

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +![Android SDK Installation](https://github.com/ExNDY/kmm.icerock.dev/blob/movement_workspace_dir/learning/android_sdk_setup.jpg "Android SDK Installation")
путь кривой :)
`android_sdk_setup.jpg` поставь

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +![environment complete for .zshenv](https://github.com/ExNDY/kmm.icerock.dev/blob/movement_workspace_dir/learning/environment_complete_example.png "Completed .zshenv")
тож путь кривой

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +![move xcode in other dir](https://github.com/ExNDY/kmm.icerock.dev/blob/movement_workspace_dir/learning/move_xcode_in_other_dir.png "Move Xcode.app in App folder")
кривой путь

2022-08-03 09:32 UTC, Alex009 commented on learning/movement_workspace_dir.md
> +![location of workspace dir in Xcode preferences](https://github.com/ExNDY/kmm.icerock.dev/blob/movement_workspace_dir/learning/change_xcode_paths_workdir.png "Xcode workspace dir")
кривой путь)

2022-08-03 11:32 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +`export KONAN_DEV_DIR=/Volumes/ExternalDrive/KONAN/.konan`
Действительно, как-то забежала сюда ошибка

2022-08-05 17:42 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +  `/%USERNAME%/.gradle`
fixed

2022-08-05 17:42 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +  `/%USERNAME%/.konan`
fixed

2022-08-05 17:42 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +  `/%USERNAME%/Documents/xCode`
fixed

2022-08-05 17:42 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +  `/%USERNAME%/AndroidStudioProjects`
fixed

2022-08-05 17:43 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +Для экономии времени можем перенести папку .konan из директории `/%USERNAME%/.konan` в заранее созданную нами папку.
fixed

2022-08-05 17:43 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +![Android SDK Installation](https://github.com/ExNDY/kmm.icerock.dev/blob/movement_workspace_dir/learning/android_sdk_setup.jpg "Android SDK Installation")
fixed

2022-08-05 17:43 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +![environment complete for .zshenv](https://github.com/ExNDY/kmm.icerock.dev/blob/movement_workspace_dir/learning/environment_complete_example.png "Completed .zshenv")
fixed

2022-08-05 17:43 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +![move xcode in other dir](https://github.com/ExNDY/kmm.icerock.dev/blob/movement_workspace_dir/learning/move_xcode_in_other_dir.png "Move Xcode.app in App folder")
fixed

2022-08-05 17:43 UTC, ExNDY commented on learning/movement_workspace_dir.md
> +![location of workspace dir in Xcode preferences](https://github.com/ExNDY/kmm.icerock.dev/blob/movement_workspace_dir/learning/change_xcode_paths_workdir.png "Xcode workspace dir")
fixed

2022-08-07 15:05 UTC, Alex009 approved these changes

2022-08-07 15:12 UTC, merged