Add swiftui optimization.
icerockdev/kmm-docs pull request #157
Opened 2023-11-24 08:10 UTC by bullinnyc

2023-11-27 05:46 UTC, Alex009 requested changes

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-10.png
вместо скриншотов кода используй вставки кода через блок code. Чтоб было как тут:

```swift
struct Test: View {
}
```

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-11.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-13.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-14.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-15.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-16.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-17.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-18.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-2.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-3.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-6.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-7.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/demo-8.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/onAppear.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/onDisappear.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization/view-hierarchy.png
тоже заменить на вставку блока кода

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization.md
> +# Жизненный цикл SwiftUI
так статья про жизненный цикл или про оптимизацию swiftui? название файла не соответствует заголовку страницы.

2023-11-27 05:46 UTC, Alex009 commented on learning/ios/swiftui-optimization.md
> +**ViewGraph**
разделы пишутся через две решетки - ## так это будет заглоовок.

# Одна решетка - название страницы
## Две решетки - блок страницы с заголовком
### Три решетки - раздел в блоке

2023-11-27 08:05 UTC, bullinnyc commented on learning/ios/swiftui-optimization.md
> +# Жизненный цикл SwiftUI
Поправил название файла и заголовок.

2023-12-07 12:08 UTC, Alex009 approved these changes

2023-12-07 12:08 UTC, merged