create gradle daemon desc
icerockdev/kmm-docs pull request #41
Opened 2021-08-24 05:27 UTC by kramlex

added a description of the Gradle Daemon in the Documentation -> For ios developers -> Gradle

2021-08-24 05:30 UTC, Alex009 requested changes

2021-08-24 05:30 UTC, Alex009 commented on docs/for-ios-devs/gradle.md
> +# Gradle Daemon
передвинь это выше, где про градл в принципе описано.

2021-08-24 05:30 UTC, Alex009 commented on docs/for-ios-devs/gradle.md
> +# Gradle Daemon
сразу после блока "Gradle"

2021-08-24 05:41 UTC, kramlex commented on docs/for-ios-devs/gradle.md
> +# Gradle Daemon
Готово

2021-08-25 02:15 UTC, Alex009 approved these changes

2021-08-25 02:15 UTC, merged