#23 project inside
icerockdev/kmm-docs pull request #43
Opened 2021-08-31 09:39 UTC by kramlex

changing the"Project Inside" page

2021-09-06 01:47 UTC, Alex009 requested changes

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +- `build-logic` - подпроект, подключе;
что-то тут не дописано

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +- `README.md` - краткое описание содержимого репозитория и инструкция как собирать проект;
а почему тут в конце `;` вместо точки стало? :)

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +:::
надо это в начало раздела поставить. чтобы сразу было ясно почему "устарело" метка стоит

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +На новых проектах внутри директории `gradle` есть файл `libs.versions.toml`. Это список зависимостей, представленных в виде координат зависимостей, из которых пользователь может выбрать при объявлени
очень запутанно сформулированно)

Это список зависимостей, на основе которого gradle сгенерирует специальные свойства для доступа к зависимостям по именам со строгими типами, данный файл позволяет централизованно управлять зависимостями всего проекта. 
Подробнее - <ссылка на раздел в обучении>

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +На новых проектах внутри директории `gradle` есть файл `libs.versions.toml`. Это список зависимостей, представленных в виде координат зависимостей, из которых пользователь может выбрать при объявлени
ну и все что дальше идет я думаю надо утащить в раздел про обучение, чтобы конкретная тема была в одном месте

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +В этой директории можно увидеть собственный `build.gradle.kts` и исходный код библиотеки. `build.gradle.kts` определяет как будет собираться данная библиотека и какие зависимости ей требуются. Исходн
ссылки на страницу обучения про конвеншн плагины не хватает

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
>  Использование `gradle.properties` это альтернатива использованию флагов командной строки для конфигурации проекта.
помимо тех настроек что уже есть в проекте нужно еще упомянуть что важно настраивать свое локальное окружение под производительность. инфа про это должна быть в разделе обучение, на который отсюда надо сослаться

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +# не распространять конфигурацию на все проекты
нет. это опция про отложенную конфигурацию - типа когда градл конфигурирует проект только в тот момент, когда от проекта что-то потребовалось. это должно ускорять работу гредла, но по факту до сих пор слабо поддерживается плагинами и поэтому часто тупо крешится все. поэтому мы выключаем эту опцию.

https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:configuration_on_demand

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +Этот файл необходим для сборки с несколькими проектами, в нашем случае это `android-app`, `mpp-library` и `mpp-library:feature:auth`, `build-logic`.
давай более правильное описание напишем. "Этот файл определяет настройки gradle проекта. здесь мы можем подключать под-проекты (вызовом include) и подключать другие gradle проекты, настраивая composite build (вызовом includeBuild)"

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +    id("dev.icerock.gradle.talaiot") version("3.+")
надо указать зачем тут плагин талаиота :)
он в settings для того, чтобы автоматически включать и gradle build scan https://docs.gradle.com/enterprise/gradle-plugin/
да, в settings тоже можно применять плагины

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +Эти зависимости будут также автоматически подключены и к самому Gradle проекту, поэтому плагины из этих зависимостей мы можем применять без добавления артефактов в `classpath`.
какие "эти"?

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +        classpath(":build-logic")
надо подмержить актцальный moko-template в бойлерплейт - там уже вместо строк тут используется version catalog (начиная с 7.2 доступно стало)

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +    id("dev.icerock.mobile.multiplatform.cocoapods")
надо подробнее - кто тут и зачем

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +    commonTestImplementation(libs.ktorClientMock)
надо указать зачем тут этот огромный список

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +    export(libs.mokoCrashReportingNapier)
это не подключение. это экспорты в ios фреймворк - https://kotlinlang.org/docs/reference/mpp-build-native-binaries.html#export-dependencies-to-binaries
надо это пояснить и ссылку на доку поставить

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +}
все не так :) это подключение **внутрь** общей библиотеки нативной либы `MCRCDynamicProxy` - то есть нативный cocoapods подключить внутрь kotlin кода

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +}
зачем что почему? :) и ссылку на моко нетворк надо

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +В папке `srs/` находится исходный код общей библиотеки.
src

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +Более подробно об этом файле мы уже говорили в разделе [сборка iOS приложения](https://kmm.icerock.dev/onboarding/project-inside/#сборка-ios-приложения).
а может выдернем это в отдельный блок в learning? например там уже есть Kotlin/Native раздел - давай там и опишем на странице про интеграцию cocoapods (она уже есть) все то что тут щас у нас про подспек расписано. а отсюда будем просто ссылаться туда

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> + - директория `commonMain` содержит директорию `kotlin`, в которой как раз и пишется вся бизнес-логика приложения; в директории `resources` находится MR-класс для взаимодействия со строками, изображе
в директории `resources` валяются ресурсы, которые через moko-resources попадают в наш проект.

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +- `presentation` - директория, содержащая саму view-model и, возможно, фабрику юнитов (об этом поговорим дальше).
фича не завязана на одну вьюмодель и может быть вообще не связанной с ui - без вьюмодели. может быть с множеством вьюмоделей. фича это функциональность некоторая, типа "store" где логика всего магазина (и просмотр вариантов подписки и подписка например) и "notifications" где и логика регистрации токена пушей и вьюмодель просмотра списка уведомлений....это я к тому что в описании не должно быть все завязано на одну вьюмодель

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +- `presentation` - директория, содержащая саму view-model и, возможно, фабрику юнитов (об этом поговорим дальше).
а в `model` помимо сущностей еще определяются интерфейсы репозиториев, откуда мы эти сущности сможем получать и куда сможем их закидывать

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +Т.к каждая фича является отдельной Gradle-библиотекой, то она обязана содержать файл `AndroidManifest.xml`, в котором объявляется уникальное имя для Android-приложения.
подробнее надо про packageId манифеста. на нем постоянно айосники фейлятся и андроид потом не собирается :) нужно раскрыть мысль - во всем проекте каждый androidmanifest должен иметь уникальный packageId, так как если пересекутся то андроид приложение вообще не соберется. этот packageId используется для генерации специальных классов android, поэтому при одинаковых id получается несколько одинаковых классов

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +Мы стараемся делать фичи максимально независящими от контекста проекта. Иными словами — фича должна знать ровно тот набор информации, который ей нужен для корректной работы в рамках самой себя. При э
При этом важно сократить до минимума её зависимости от каких либо других модулей. **Делается это для ускорения времени сборки проекта.** Наиболее критично такое сказывается на времени компиляции под iOS, когда проект уже разросся.

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +Мы стараемся делать фичи максимально независящими от контекста проекта. Иными словами — фича должна знать ровно тот набор информации, который ей нужен для корректной работы в рамках самой себя. При э
и в конце, после примера про shared, указать "поэтому мы стремися делать фичи полностью независимыми, не имеющими никаких локальных зависимостей (кроме тех, которые изменяются крайне редко)"

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
> +// импорт сервисов
внешних зависимостей импорт тут

2021-09-06 01:47 UTC, Alex009 commented on onboarding/3-project-inside.md
>  нашей первой фичи.
создание фичи этож вообще про другое :) в кодлабе это. а тут про создание не должно быть

2021-09-06 09:56 UTC, kramlex commented on onboarding/3-project-inside.md
> +- `README.md` - краткое описание содержимого репозитория и инструкция как собирать проект;
Так и было. Я все списки оформляю по тому что было)

2021-09-06 09:59 UTC, kramlex commented on onboarding/3-project-inside.md
> +На новых проектах внутри директории `gradle` есть файл `libs.versions.toml`. Это список зависимостей, представленных в виде координат зависимостей, из которых пользователь может выбрать при объявлени
Отметил для себя, будет сделано

2021-09-06 10:01 UTC, kramlex commented on onboarding/3-project-inside.md
> +В этой директории можно увидеть собственный `build.gradle.kts` и исходный код библиотеки. `build.gradle.kts` определяет как будет собираться данная библиотека и какие зависимости ей требуются. Исходн
Добавил

2021-09-06 10:07 UTC, kramlex commented on onboarding/3-project-inside.md
> +Т.к каждая фича является отдельной Gradle-библиотекой, то она обязана содержать файл `AndroidManifest.xml`, в котором объявляется уникальное имя для Android-приложения.
Ну вообще про устройство android мира для ios'ников и про устройство iOS мира для android'щиков можно сделать отдельную статью в обучении.

2021-09-06 10:11 UTC, kramlex commented on onboarding/3-project-inside.md
>  нашей первой фичи.
Ну тут имелось ввиду, что после прочтения пункта 3 в онбординге сразу переходим к след пункту, в котором кодлаба

2021-09-07 04:18 UTC, kramlex commented on onboarding/3-project-inside.md
> +:::
Поправил; так будет нагляднее

2021-09-07 04:24 UTC, kramlex commented on onboarding/3-project-inside.md
> +На новых проектах внутри директории `gradle` есть файл `libs.versions.toml`. Это список зависимостей, представленных в виде координат зависимостей, из которых пользователь может выбрать при объявлени
Написал более понятным языком что такое version catalog, впрнц мне кажется не стоит уносить содержимое файла в раздел обучения, просто ты в видосе показываешь из чего состоит этот файл + как подключается эта фича в settings.gradle.kts. Можно это тут оставить, чтоб люди видели какие версии библиотек подключаются именно в бойлерплейт шаблоне.

2021-09-07 04:26 UTC, kramlex commented on onboarding/3-project-inside.md
>  Использование `gradle.properties` это альтернатива использованию флагов командной строки для конфигурации проекта.
Мы эту тему осветили в кодлабе, впрнц настройка окружения для комфортной работы делается один раз, после чего мы не возвращаемся к настройке локального gradle.properties. Что думаешь?

2021-09-07 04:29 UTC, kramlex commented on onboarding/3-project-inside.md
> +# не распространять конфигурацию на все проекты
Запомнил, отписал это в комментарии

2021-09-07 04:33 UTC, kramlex commented on onboarding/3-project-inside.md
> +Этот файл необходим для сборки с несколькими проектами, в нашем случае это `android-app`, `mpp-library` и `mpp-library:feature:auth`, `build-logic`.
Исправлено

2021-09-07 04:38 UTC, kramlex commented on onboarding/3-project-inside.md
> +    id("dev.icerock.gradle.talaiot") version("3.+")
// В настройках тоже можно подключать плагины.
// Данный плагин является настройкой плагина Gradle Talaiot.
// Он отправляет статистику сборки в аналитическую базу данных
// нашей компании.
отписал в комментарии для чего нужен этот плагин в settings.gradle.kts

2021-09-07 04:38 UTC, Alex009 commented on onboarding/3-project-inside.md
>  Использование `gradle.properties` это альтернатива использованию флагов командной строки для конфигурации проекта.
упомянуть же не мешает. и настройку окружения под себя стоит на страничицу в Learning выделить (в группе gradle)

2021-09-07 04:40 UTC, kramlex commented on onboarding/3-project-inside.md
>  Использование `gradle.properties` это альтернатива использованию флагов командной строки для конфигурации проекта.
Окей, дублирование с кодлабой тогда оставляем?

2021-09-07 04:49 UTC, kramlex commented on onboarding/3-project-inside.md
> +Эти зависимости будут также автоматически подключены и к самому Gradle проекту, поэтому плагины из этих зависимостей мы можем применять без добавления артефактов в `classpath`.
Просто удалил этот текст, оставив только код из файла и ссылку на статью обучения в которой подробно описано как конфигурируются зависимости

2021-09-08 02:37 UTC, kramlex commented on onboarding/3-project-inside.md
> +- `build-logic` - подпроект, подключе;
Исправлено

2021-09-10 04:15 UTC, Alex009 requested changes

2021-09-10 04:15 UTC, Alex009 commented on learning/gradle/build-environment.md
> +- В проекте  - свойства проекта применяются ко всему проекту Gradle, например, к проекту moko-template. Используйте свойства на уровне проекта для управления номерами версий библиотек и других ресурс
номера версий библиотек не надо советовать в проперти тащить. не наш подход

2021-09-10 04:15 UTC, Alex009 commented on learning/gradle/build-environment.md
> +# отключение ошибок, возникших в ios таргете
предупреждение о использовании шортката ios() отключает это, а не ошибок

2021-09-10 04:15 UTC, Alex009 commented on learning/gradle/build-environment.md
> +VERSION_CODE=1
это только для андроида указывает версию. надо явно указать это, айос меняется в другом месте. и это единственное версионирование окторое через файл пропертис у нас :)

2021-09-10 04:15 UTC, Alex009 commented on learning/gradle/build-environment.md
> +# переменная, хранящая путь до нашего xcode-проекта
для AS плагина Kotlin Multiplatform Mobile

2021-09-10 04:15 UTC, Alex009 commented on learning/gradle/build-environment.md
> +Настройками глобального окружения вы как раз займетесь в [нашей кодлабе](https://codelabs.kmp.icerock.dev/codelabs/kmm-icerock-onboarding-1-ru/index.html#1) на этапе "Настройка рабочего окружения".
нужно тут в нашей странице указать рекомендуемые настройки - чтоб не надо было вечно в кодлабу идти перелистывать

2021-09-10 04:15 UTC, Alex009 commented on learning/gradle/updating-versions.md
> +то при смене минорной версии `1.4.21 ~> 1.5.21` ничего не должно сломаться.
гдеж тут минорная то меняется? мажорная сменилась - 1.4 на 1.5 сдвинулся. тут как раз и может все сломаться. 
суть в том что безопасно поднимать версию можно в пределах одной мажорной версии - с 1.4.10 на 1.4.20 например. а с 1.4.21 до 1.5.0 если поднимать то нужно обязательно проверять компиляцию обеих платформ и что все в рантайме осталось работать. скорее всего придется и версии библиотек обновлять на те, которые поддерживают новую мажорную версию

2021-09-10 04:15 UTC, Alex009 commented on learning/gradle/updating-versions.md
> +При обновлении мажорных версий, например Gradle `6.9.1 ~> 7.0.2`
вот с гредлом редко бывает чтобы чето сломалось при поднятии версии

2021-09-10 04:15 UTC, Alex009 commented on learning/ios/navigation.md
> +class BaseCoordinator: NSObject, Coordinator, UINavigationControllerDelegate {
не надокод всей реализации сюда тащить - нужно только публичное апи

2021-09-15 02:08 UTC, Alex009 requested changes

2021-09-15 02:08 UTC, Alex009 commented on learning/ios/navigation.md
> +class BaseCoordinator: NSObject, Coordinator, UINavigationControllerDelegate {
детали реализации не надо нам тут хранить

2021-09-15 02:08 UTC, Alex009 commented on learning/ios/pods.md
> +# Cocoa Pods
слитно пишется :)

2021-09-15 02:08 UTC, Alex009 commented on learning/ios/pods.md
> +# Запрещает все "варнинги" от библиотек CocoaPods.
warning'и тогда уж :)

2021-09-15 02:08 UTC, Alex009 commented on learning/ios/pods.md
> +В нашем же проекте их 6, и, как мы видим, благодаря верно указанным ключам для каждой конфигурации, в `Build Settings` у нас различные макросы для препрцессора на каждый тип конфигурации:
надо отсылку указать на билдконфиги, которые описаны уже в ios конфиге

2021-09-15 02:08 UTC, Alex009 commented on learning/libraries/publication.md
> +Добавление новых целей для мультиплатформенной библиотеки со стороны потребителя не поддерживается.
новых таргетов. цели тут не звучат совсем

2021-09-15 02:08 UTC, Alex009 commented on learning/libraries/publication.md
> +Библиотека, созданная из многоплатформенного проекта, может быть опубликована в репозитории Maven с плагином Gradle `maven-publish`, который может применяться следующим образом:
сначала стоит скахать что такое мавен репозиторий

2021-09-15 02:08 UTC, Alex009 commented on learning/libraries/publication.md
> +При применении данного плагина публикации по умолчанию создаются для каждой из целей, которая может быть создана на текущем хосте. Увидеть это можно, заглянув в [IceRock Moko Maven репозиторий](https
moko/MOKO 
не Moko

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +- `gradle` - директория [Gradle Wrapper'а](/learning/gradle/gradle-wrapper) - специального скрипа, который автоматизирует процесс установки нужной версии gradle.
скрипта

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +- `build-logic` - композитно подключенный проект, несущий в себе логику сборки остальных подпроектов;
ссылку на блок про композитные билды надо, а то слово сказали новое а пояснений нет

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +На новых проектах вместо `buildSrc` используется `Version Catalogs`.
используется композитный билд. это он является заменой buildSrc. а вершн каталоги заменяют класс Deps.

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +Больше информации о Version Catalogs можете найти [тут](https://kmm.icerock.dev/learning/gradle/version-catalogs/).
ссылку надо относительную, без хостнейма

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +- `build-logic` - композитно подключенный проект, несущий в себе логику сборки остальных подпроектов;
или укажи что про композит чуть  позже поясним

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +В этой директории можно увидеть собственный `build.gradle.kts` и исходный код библиотеки. `build.gradle.kts` определяет как будет собираться данная библиотека и какие зависимости ей требуются. Исходн
тоже относительные ссылки надо

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +`build-logic` - [композитный](https://kmm.icerock.dev/learning/gradle/composite-build) проект. Он предназначен для реализации логики сборки, не привязанной к конкретному gradle модулю.
тоже относительные ссылки надо

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +// подключение фичей (начиная с Gradle 7.0)
подкючение фичей не с 7.0 началось. это эти конкретные фичи только в 7 появились и пока являются preview

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +    // репозитории, из которых будут загружаться зависимости проекта
тут репозитории только для плагинов

2021-09-15 02:08 UTC, Alex009 commented on onboarding/3-project-inside.md
> +В папке `srs` находится исходный код общей библиотеки.
src, я уже обращал на это внимание

2021-09-16 07:31 UTC, kramlex commented on onboarding/3-project-inside.md
> +    export(libs.mokoCrashReportingNapier)
Добавил ссылку.

2021-09-16 07:37 UTC, kramlex commented on onboarding/3-project-inside.md
> +В папке `srs/` находится исходный код общей библиотеки.
Исправлено

2021-09-16 07:38 UTC, kramlex commented on onboarding/3-project-inside.md
> +Более подробно об этом файле мы уже говорили в разделе [сборка iOS приложения](https://kmm.icerock.dev/onboarding/project-inside/#сборка-ios-приложения).
Добавлен раздел Pods в iOS Learning

2021-09-17 02:00 UTC, merged

2021-09-17 02:53 UTC, kramlex commented on onboarding/3-project-inside.md
> +В папке `srs` находится исходный код общей библиотеки.
Исправлено

2021-09-17 02:53 UTC, kramlex commented on onboarding/3-project-inside.md
> +    // репозитории, из которых будут загружаться зависимости проекта
Исправлено

2021-09-17 02:53 UTC, kramlex commented on onboarding/3-project-inside.md
> +// подключение фичей (начиная с Gradle 7.0)
Исправлено

2021-09-17 02:54 UTC, kramlex commented on onboarding/3-project-inside.md
> +`build-logic` - [композитный](https://kmm.icerock.dev/learning/gradle/composite-build) проект. Он предназначен для реализации логики сборки, не привязанной к конкретному gradle модулю.
Исправлено

2021-09-17 02:54 UTC, kramlex commented on onboarding/3-project-inside.md
> +В этой директории можно увидеть собственный `build.gradle.kts` и исходный код библиотеки. `build.gradle.kts` определяет как будет собираться данная библиотека и какие зависимости ей требуются. Исходн
Исправлено

2021-09-17 02:57 UTC, Alex009 commented on onboarding/3-project-inside.md
> +    export(libs.mokoCrashReportingNapier)
а куда именно добавил? найти не могу

2021-09-17 03:40 UTC, kramlex commented on onboarding/3-project-inside.md
> +    export(libs.mokoCrashReportingNapier)
После кода build.gradle.kts:
Для того, чтобы понять как происходит экспорты зависимостей в iOS-фреймворк, можете ознакомиться с [соответствующей статьей](/learning/kotlin-native/cocoapods) в разделе обучения.

2021-09-17 03:46 UTC, kramlex commented on learning/libraries/publication.md
> +Добавление новых целей для мультиплатформенной библиотеки со стороны потребителя не поддерживается.
Исправлено

2021-09-17 03:46 UTC, kramlex commented on learning/libraries/publication.md
> +Библиотека, созданная из многоплатформенного проекта, может быть опубликована в репозитории Maven с плагином Gradle `maven-publish`, который может применяться следующим образом:
Добавлена иснформация о том, что такое равен репозотирий

2021-09-17 03:48 UTC, kramlex commented on onboarding/3-project-inside.md
> +- `build-logic` - композитно подключенный проект, несущий в себе логику сборки остальных подпроектов;
Указал ссылку!

2021-09-17 03:48 UTC, kramlex commented on onboarding/3-project-inside.md
> +- `gradle` - директория [Gradle Wrapper'а](/learning/gradle/gradle-wrapper) - специального скрипа, который автоматизирует процесс установки нужной версии gradle.
Исправлено

2021-09-17 03:49 UTC, kramlex commented on onboarding/3-project-inside.md
> +На новых проектах вместо `buildSrc` используется `Version Catalogs`.
Исправил, добавил в раздел версион каталог, про то что он заменяет объект Deps

2021-09-17 03:53 UTC, kramlex commented on learning/libraries/publication.md
> +При применении данного плагина публикации по умолчанию создаются для каждой из целей, которая может быть создана на текущем хосте. Увидеть это можно, заглянув в [IceRock Moko Maven репозиторий](https
Поправил в другом ПР

2021-09-17 04:26 UTC, Alex009 commented on onboarding/3-project-inside.md
> +    export(libs.mokoCrashReportingNapier)
ты делаешь отсылку не на то что я попросил указать.