Add learning page for moko-paging
icerockdev/kmm-docs pull request #48
Opened 2021-09-03 13:33 UTC by RezMike

2021-09-06 15:30 UTC, Alex009 requested changes

2021-09-06 15:30 UTC, Alex009 commented on learning/moko/moko-paging.md
> +         a.id - b.id
почему тут минус? `a.id.compare(b.id)` можно ведь

2021-09-06 15:30 UTC, Alex009 commented on learning/moko/moko-paging.md
> +Также можно использовать сравнение хешей или любой другой способ:
сравнение должно выдавать true для тех объектов, которые по правде являются теми же самыми (в идеале по id). иначе можно получить дубликаты (сравнение сейчас только определяет какое количество полученных с сервера элементов нужно присоединить к существующему списку)

2021-09-06 15:30 UTC, Alex009 commented on learning/moko/moko-paging.md
> +val data: LiveData<List<Data>> = pagination.state.data()
nullable

2021-09-06 15:30 UTC, Alex009 commented on learning/moko/moko-paging.md
> +val error: LiveData<Throwable?> = pagination.state.error()
зачем тут throwable выдавать наружу? преобразованный к StringDesc вариант мы в проектах выдаем

2021-09-06 15:30 UTC, Alex009 commented on learning/moko/moko-paging.md
> +лучше использовать отдельную `MutableLiveData`:
вот это странный совет, а если у нас пагинированный список фотографий пользователя и юзер может удалить любое из этих фото - тут ведь и надо юзать setData, да? а предложенный вариант это не для модификации пагинированных данных, а для добавления к ним чего-то дополнительного...верно?

2021-09-18 16:54 UTC, RezMike commented on learning/moko/moko-paging.md
> +         a.id - b.id
да, лучше использовать compareTo

2021-09-18 17:02 UTC, RezMike commented on learning/moko/moko-paging.md
> +Также можно использовать сравнение хешей или любой другой способ:
немного изменил формулировку и убрал сравнение по хеш-кодам

2021-09-18 17:04 UTC, RezMike commented on learning/moko/moko-paging.md
> +val data: LiveData<List<Data>> = pagination.state.data()
исправил

2021-09-18 17:07 UTC, RezMike commented on learning/moko/moko-paging.md
> +val error: LiveData<Throwable?> = pagination.state.error()
исправил

2021-09-18 17:14 UTC, RezMike commented on learning/moko/moko-paging.md
> +лучше использовать отдельную `MutableLiveData`:
изменил формулировку

2021-09-22 07:41 UTC, merged