Add guide "Forced FCM token invalidation"
icerockdev/kmm-docs pull request #99
Opened 2022-04-23 10:02 UTC by EvelDevel

2022-05-09 12:07 UTC, Alex009 requested changes

2022-05-09 12:07 UTC, Alex009 commented on learning/ios/forced_fcm_invalidation.md
> +## Проект: [Spota](https://apps.apple.com/ru/app/spota-app/id1534762445)
эту ссылку стоит убрать, к теме не относится)

2022-05-09 12:07 UTC, Alex009 commented on learning/ios/forced_fcm_invalidation.md
> +## Наш кейс:
двоеточия в заголовках не нужны

2022-05-09 12:07 UTC, Alex009 commented on learning/ios/forced_fcm_invalidation.md
> +```
все это надо сократить до самого метода инвалидации токена, с пояснением как им пользоваться. когда его вызывать разработчик конкретного проекта сам решит

2022-05-11 06:36 UTC, EvelDevel commented on learning/ios/forced_fcm_invalidation.md
> +```
Все пофиксил, обновил реквест

2022-05-12 06:47 UTC, Alex009 approved these changes

2022-05-12 06:54 UTC, merged